### ISSUE TITLE
export onnx model fails: no module named 'import_onnx'

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#247]
I uninstalled the previous pip version and built from source to get the new onnx support. 
I used the synset, signature, and onnx example files.
I ran the command as described in the new docs for onnx support.

```
(mxnet3.6) 8c8590217d26:onnx markhama$ mxnet-model-export --model-name squeezenet_v1.1 --model-path . --from-type onnx
/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.1.5-py3.6.egg/mms/export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/markhama/Development/mxnet3.6/bin/mxnet-model-export", line 11, in <module>
    load_entry_point('mxnet-model-server==0.1.5', 'console_scripts', 'mxnet-model-export')()
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.1.5-py3.6.egg/mms/export_model.py", line 255, in export
    export_model(args.model_name, args.model_path, args.from_type, args.service_file_path)
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.1.5-py3.6.egg/mms/export_model.py", line 209, in export_model
    convert_to_mxnet(model_path, from_type)
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.1.5-py3.6.egg/mms/export_model.py", line 196, in convert_to_mxnet
    import onnx_mxnet
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/onnx_mxnet-0.2-py3.6.egg/onnx_mxnet/__init__.py", line 12, in <module>
ModuleNotFoundError: No module named 'import_onnx'
(mxnet3.6) 8c8590217d26:onnx markhama$ 
```

**Comment by lupesko** [comment]
You may be missing onnx-mxnet PyPi package.

How did you install the code?
If you used `python setup.py` then it *does not* install dependencies.
It is preferred to use `pip install . --upgrade` which installs dependencies.

Can you please check?

**Comment by Roshrini** [comment]
This issue seems to be with python3. Fix was submitted but probably need to create new pip package for onnx-mxnet. I will create it in some time.

**Comment by aaronmarkham** [comment]
Also, please check on the CI in case we don't have a test for this kind of failure.

**Comment by aaronmarkham** [comment]
Updates in onnx-mxnet have resolved this issue.
