### ISSUE TITLE
exporting Pytorch ONNX file fails on Ubuntu DLAMI

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#304]
Using the Ubuntu Deep Learning AMI to export a PyTorch model fails.

```
(mxnet_p27) ubuntu@ip-172-31-15-141:~/alexnet$ mxnet-model-export --model-name onnx-alexnet --model-path .
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/bin/mxnet-model-export", line 11, in <module>
    sys.exit(export())
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mms/export_model.py", line 256, in export
    export_model(args.model_name, args.model_path, args.service_file_path)
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mms/export_model.py", line 210, in export_model
    convert_to_mxnet(model_path)
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/mms/export_model.py", line 198, in convert_to_mxnet
    import onnx_mxnet
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/onnx_mxnet/__init__.py", line 13, in <module>
    import onnx
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /home/ubuntu/anaconda3/envs/mxnet_p27/lib/python2.7/site-packages/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev
```

The alexnet model was prepared according to the PyTorch export to ONNX docs:

```
from torch.autograd import Variable
import torch.onnx
import torchvision

dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
model = torchvision.models.alexnet(pretrained=True).cuda()
torch.onnx.export(model, dummy_input, "alexnet.proto", verbose=True)
```

Also tried `torchvision.models.squeezenet1_1` and this model gives the same error. 
Also tried both the p36 and p27 Conda environments.

Various github issues seem to indicate problem could be with the protobuf version/build process on Ubuntu.

**Comment by lupesko** [comment]
Closed since this is an issue specific to AWS DL AMI, not MMS.
