### ISSUE TITLE
error message for lack of appropriate model files not displaying properly

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#305]
I this example I'm using the .proto extension as the onnx formatted file.

I expected to be provided with the requirements error text similar to the first error text I provided [here](https://github.com/awslabs/mxnet-model-server/issues/257). It should say that it can take a .onnx file or symbol/params...

```
(mxnet3.6) 8c8590217d260a:pytorch-alexnet markhama$ mxnet-model-export --model-name pytoch-onnx-alexnet --model-path .
/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/markhama/Development/mxnet3.6/bin/mxnet-model-export", line 11, in <module>
    load_entry_point('mxnet-model-server==0.2', 'console_scripts', 'mxnet-model-export')()
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/export_model.py", line 256, in export
    export_model(args.model_name, args.model_path, args.service_file_path)
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/export_model.py", line 223, in export_model
    symbol_file = validate_symbol(model_path)
  File "/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mxnet_model_server-0.2-py3.6.egg/mms/export_model.py", line 106, in validate_symbol
    % (str(sym_files), model_path)
AssertionError: should have 1 symbol file ending with -symbol.json in the filename, given:[] in model_path:./
(mxnet3.6) 8c8590217d260a:pytorch-alexnet markhama$ ls
alexnet.proto	signature.json	synset.txt
```

**Comment by jesterhazy** [comment]
are you running current version of mms?
