### ISSUE TITLE
Invalid syntax for version number

### ISSUE THREAD

**Issue by Roshrini** [awslabs/mxnet-model-server#395]
Installed MMS with following command:
pip install --pre mxnet-model-server

Got error while running mxnet-model-server command:

```
roshanin$ mxnet-model-export --model-name="pretrained-alexnet" --model-path="/tmp/models" --service-file-path="/tmp/models/gluon_pretrained_alexnet.py"
/Users/roshanin/anaconda2/lib/python2.7/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/Users/roshanin/anaconda2/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py:46: DeprecationWarning: OpenSSL.rand is deprecated - you should use os.urandom instead
  import OpenSSL.SSL
Traceback (most recent call last):
  File "/Users/roshanin/anaconda2/bin/mxnet-model-export", line 7, in <module>
    from mms.export_model import export
  File "/Users/roshanin/anaconda2/lib/python2.7/site-packages/mms/__init__.py", line 22, in <module>
    from . import version
  File "/Users/roshanin/anaconda2/lib/python2.7/site-packages/mms/version.py", line 14
    __version__ = 0.4b2
                      ^
SyntaxError: invalid syntax
```

**Comment by vrakesh** [comment]
Yes with beta version, the version the version read within mms fails, this works fine for non beta releases. Will be a priority fix
