### ISSUE TITLE
[bug] cannot use a custom service file called 'service.py'

### ISSUE THREAD

**Issue by ThomasDelteil** [awslabs/mxnet-model-server#713]
```
2018-12-20 13:04:22,838 [INFO ] W-9002-pose-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - TypeError: __init__() missing 6 required positional arguments: 'model_name', 'model_dir', 'manifest', 'entry_point', 'gpu', and 'batch_size'
```
etc...

It is trying to use the mms built-in service.py rather than the user-provided service.py

**Comment by vdantu** [comment]
Could you share how your MANIFEST.json file looks? Also, where in the directory structure is this "MANIFEST.json" present? 

If MANIFEST.json is present in the same place as the "Model Directory" then you will see this behavior (it falls back to 0.4 behavior). If the MANIFEST.json is inside "MAR-INF/MANIFEST.json", it is treated as 1.0 behavior and you wont see this default "built-in" service file being used.

**Comment by vdantu** [comment]
In otherwords, if you use "model-archiver" to create your .mar file, you shouldn't be seeing this behavior. IF you are using "mxnet-model-export" and creating the .model file, you will see this behavior.

**Comment by ThomasDelteil** [comment]
I created it using model-archiver

**Comment by ThomasDelteil** [comment]
By the way I know that I "shouldn't be seeing this behavior", that's the definition of a bug 😄 

```
> pip list | grep mxnet-model
mxnet-model-server (1.0.1)
```
(btw would be nice to have a `mxnet-model-server --version`)

Here is how you can reproduce:
```bash
mkdir test_model
```

create the following file:
`test_model\service.py`
```python
def test(data, context):
    return [{}]
```

Then run:
```bash
model-archiver --model-name test --model-path test_model --export-path test_model --handler service:test
mxnet-model-server --start --model-store . --models test=test.mar
```

```
2018-12-21 21:06:01,294 [DEBUG] W-9001-test com.amazonaws.ml.mms.wlm.WorkerThread - Backend worker monitoring thread interrupted or backend worker process died.
java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.ArrayBlockingQueue.poll(ArrayBlockingQueue.java:418)
	at com.amazonaws.ml.mms.wlm.WorkerThread.run(WorkerThread.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-12-21 21:06:01,284 [INFO ] KQueueEventLoopGroup-4-3 com.amazonaws.ml.mms.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2018-12-21 21:06:01,294 [WARN ] W-9001-test com.amazonaws.ml.mms.wlm.BatchAggregator - Load model failed: test, error: Worker died.
2018-12-21 21:06:01,295 [DEBUG] W-9001-test com.amazonaws.ml.mms.wlm.WorkerThread - W-9001-test State change WORKER_STARTED -> WORKER_STOPPED
2018-12-21 21:06:01,294 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - Traceback (most recent call last):
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/tdelteil/anaconda3/lib/python3.6/site-packages/mms/model_service_worker.py", line 167, in <module>
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     worker.run_server()
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/tdelteil/anaconda3/lib/python3.6/site-packages/mms/model_service_worker.py", line 150, in run_server
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     self.handle_connection(cl_socket)
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/tdelteil/anaconda3/lib/python3.6/site-packages/mms/model_service_worker.py", line 116, in handle_connection
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     service, result, code = self.load_model(msg)
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/tdelteil/anaconda3/lib/python3.6/site-packages/mms/model_service_worker.py", line 96, in load_model
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size)
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -   File "/Users/tdelteil/anaconda3/lib/python3.6/site-packages/mms/model_loader.py", line 133, in load
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle -     model_service = model_class()
2018-12-21 21:06:01,295 [INFO ] W-9001-test-stdout com.amazonaws.ml.mms.wlm.WorkerLifeCycle - TypeError: __init__() missing 6 required positional arguments: 'model_name', 'model_dir', 'manifest', 'entry_point', 'gpu', and 'batch_size'
```

**Comment by ThomasDelteil** [comment]
This is the content of the service file:
```
def test(data, context):
    return [{}]
```
The service file is called `service.py`

Can you try to run the steps I outlined above so you can experience the bug yourself? Thanks

**Comment by OElesin** [comment]
Experiencing sam issue as well. Mentioned here: https://github.com/ThomasDelteil/VisualSearch_MXNet/issues/6

**Comment by ddavydenko** [comment]
We are planning to address this issue within next couple weeks, stay tuned!
