### ISSUE TITLE
Exception thrown on large responses

### ISSUE THREAD

**Issue by erandagan** [awslabs/mxnet-model-server#762]
When returning a large response from the backend worker (eg. tens of images at once), I'm seeing the following exception:

```
io.netty.handler.codec.CorruptedFrameException: Message size exceed limit: 6881420
	at com.amazonaws.ml.mms.util.codec.CodecUtils.readLength(CodecUtils.java:34)
	at com.amazonaws.ml.mms.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:60)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

The exception originates from [this line](https://github.com/awslabs/mxnet-model-server/blob/master/frontend/server/src/main/java/com/amazonaws/ml/mms/util/codec/ModelResponseDecoder.java#L60) in `ModelResponseDecoder`. It appears that any response larger than the max buffer size is dropped.

Our use case is a video processing model which returns several 100s of frames in a single prediction (~ 50MB when serialized).

I'll be happy to open a PR to address this with some guidance on what you think is the best approach here (should we make the buffer size configurable? implement stream-like reading?)

**Comment by vdantu** [comment]
@erandagan:  Thanks for offering to contributing to the code base. We welcome community contributing to MMS code base. We were planning to look into making the request/response handled by MMS a configurable parameter sometime this week as well, since we were blocked on this. But, if you are already working on a PR, please submit it. We would be more than happy to review the PR and merge it into the code base. 
As for your questions, I would recommend having this as a configurable parameter with a current value as default value. This, request/response size handled by MMS, could impact the memory consumption of MMS on hosts. If this default value is too huge it could lead to MMS choking on host with smaller memory resources :) . As for stream-like reading, did you mean that the front-end would send/receive a number of small sized data in a loop? What did you have in mind for stream-like reading?

**Comment by ddavydenko** [comment]
I would also suggest to share design proposal for streaming requests-responses as it is a no small feat for any web app solution. Very much welcome, but needs to go through rigorous review as a use case is not trivial and prone to many mistakes if not done right.

**Comment by erandagan** [comment]
Cool, I'll take a look at this tomorrow and take a shot at opening a PR.

As for the stream reading, I believe that would require a greater effort as we'll have to also stream the HTTP response itself (Netty supports this, but it will require more changes to the codebase)

**Comment by AlhelyGL** [comment]
@vdantu @harshbafna

Hi, I am having this same issue with torchserve when trying to return a large list of arrays. 
Has this issue being addressed as here in torchserve ? and if it has, could you please show me how to set the size so I don't get this error anymore ?

Thanks

```
2021-02-23 22:44:57,734 [ERROR] epollEventLoopGroup-5-6 org.pytorch.serve.wlm.WorkerThread - Unknown exception
io.netty.handler.codec.CorruptedFrameException: Message size exceed limit: 37524788
    at org.pytorch.serve.util.codec.CodecUtils.readLength(CodecUtils.java:24)
    at org.pytorch.serve.util.codec.ModelResponseDecoder.decode(ModelResponseDecoder.java:72)
    at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
    at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:834)



```

**Comment by gautam-girotra** [comment]
@AlhelyGL Did you find a solution?

**Comment by vprecup** [comment]
I've stumbled upon the same issue and was able to find the environment variable names that can change these parameters in the [ConfigManager class](https://github.com/awslabs/multi-model-server/blob/master/frontend/server/src/main/java/com/amazonaws/ml/mms/util/ConfigManager.java). So setting the MMS_MAX_REQUEST_SIZE / MMS_MAX_RESPONSE_SIZE environment variables when creating the (SageMaker) model solves the problem. @erandagan introduced the possibility to change the response size, but the code was further consolidated since then ;) 

In the case of Torch Serve, I guess you would need to use the TS_MAX_REQUEST_SIZE / ..RESPONSE_SIZE env vars instead, @AlhelyGL.
