### ISSUE TITLE
illegal hardware instruction when running model-archiver with onnx model

### ISSUE THREAD

**Issue by ahmed-shariff** [awslabs/mxnet-model-server#798]
When I execute the model-archiver it exists with the following error:
```
illegal hardware instruction (core dumped)  model-archiver --model-name model --model-path . --handler  -f
```

Command executed:
```
model-archiver --model-name model --model-path . --handler mxnet_vision_service:handle -f
```

Script used to export onnx model from a pytorch model:
``` python
import os
import torch
import json
import torchvision
import numpy as np
import caffe2.python.onnx.backend as onnx_caffe2_backend
import onnx

def export_to_onnx_and_test():
    model = torchvision.models.resnet.ResNet(block=torchvision.models.resnet.Bottleneck,
                                             layers=[1, 1, 1, 1],
                                             num_classes=10)
    model.train(False)
    dummy_input = torch.rand(1, 3, 224, 224)
    torch_out = model(dummy_input)
    os.makedirs("output_model", exist_ok=True)
    torch.onnx.export(model, dummy_input, "output_model/model.onnx", export_params=True)
    signature = {
        "inputs": [
            {
                "data_name": "data",
                "data_shape": [0, 3, 224, 224]
            }
        ],
        "input_type": "image/jpeg"
    }
    with open("output_model/signature.json", "w") as f:
        json.dump(signature, f)

    with open("output_model/synset.txt", "w") as f:
        for idx in range(10):
            f.write("{} label\n".format(idx))
    
    # testing model
    model = onnx.load("output_model/model.onnx")
    onnx.checker.check_model(model)
    prepared_backend = onnx_caffe2_backend.prepare(model)
    W = {model.graph.input[0].name: dummy_input.data.numpy()}
    c2_out = prepared_backend.run(W)
    np.testing.assert_almost_equal(torch_out.data.cpu().numpy(), c2_out[0], decimal=3)

if __name__ == "__main__":
    export_to_onnx_and_test()

```

script to run after generating the onnx model:
``` bash
cd output_model
curl -O https://raw.githubusercontent.com/awslabs/mxnet-model-server/master/examples/model_service_template/mxnet_vision_service.py
mkdir mxnet_utils
cd mxnet_utils
curl -O https://raw.githubusercontent.com/awslabs/mxnet-model-server/master/examples/model_service_template/mxnet_utils/image.py
curl -O https://raw.githubusercontent.com/awslabs/mxnet-model-server/master/examples/model_service_template/mxnet_utils/ndarray.py
cd ../
model-archiver --model-name model --model-path . --handler mxnet_vision_service:handle -f
```

os: arch linux (kernel: 5.0.5-arch1-1-ARCH)
python:                       3.7
python packages installed from pip:
numpy:                       1.14.6     
onnx:                          1.5.0
mxnet-mkl:                 1.4.0.post0
(mxnet also give the same problem)
mxnet-model-server:  1.0.3
protobuf                      3.7.1 
torch                           1.0.1.post2 
torchvision                  0.2.2.post3

**Comment by vdantu** [comment]
@ahmed-shariff : Could you provide more context.
1. What are you trying to achieve? Are you trying to package an ONNX model into the model archive or are you trying to convert an onnx model to an MXNet model? 
2. You are running `model-archiver` on current directory. What does your current directory have? Could you share a `ls -la` of all the files you are trying package into your model archive?

**Comment by ahmed-shariff** [comment]
@vdantu thank you for the quick response.
1. I am trying to package an ONNX model into a model archive so that I can serve it using MMS
2. The contents of the directory are all generated by the scripts I've included. The `ls -la` output of the directory:
```
total 31616
drwxr-xr-x 3 shariff shariff     4096 May 10 17:22 .
drwxr-xr-x 4 shariff shariff     4096 May 10 17:58 ..
-rw-r--r-- 1 shariff shariff 32346537 May 10 17:22 model.onnx
drwxr-xr-x 2 shariff shariff     4096 May 10 17:22 mxnet_utils
-rw-r--r-- 1 shariff shariff     2943 May 10 17:22 mxnet_vision_service.py
-rw-r--r-- 1 shariff shariff       95 May 10 17:22 signature.json
-rw-r--r-- 1 shariff shariff       80 May 10 17:22 synset.txt
```
`tree -a` of the directory:
```
.
├── model.onnx
├── mxnet_utils
│   ├── image.py
│   └── ndarray.py
├── mxnet_vision_service.py
├── signature.json
└── synset.txt

1 directory, 6 files
```

**Comment by vdantu** [comment]
@ahmed-shariff : Thanks for sharing this. 

So, your local directory has all the files and model files required to serve the model. Couple of points, 
1. Model-archiver tries to convert your onnx model to a MXNet model. So, possibly your issue is coming from ONNX to MXNet conversion.
2. I tried running the same command on "squeezenet" model downloaded from ONNX model zoo and having all the files you have shown above, and it seems to work. Would you be able to share your ONNX file model file, so that we can try?

Also, please share the output of `pip show model-archiver`.

**Comment by ahmed-shariff** [comment]
I can understand the confusion :D

Were you able to run the scripts above?

I ran into this problem with my own models. For the purpose of testing and reproducing, I initialized a resnet model using torchvision and exported the model with it's initial parameters. I tar'd the whole directory with the onnx model for your reference ([file](https://drive.google.com/file/d/1liwy9KPhga6lnMM4R3kkSfkK7MHpUfQa/view?usp=sharing)).

I also tried the squeezenet from https://github.com/onnx/tutorials/blob/master/tutorials/ONNXMXNetServer.ipynb with the model-archiver command, and still get the same error:
```
$ tree -a
.
├── mxnet_utils
│   ├── image.py
│   └── ndarray.py
├── mxnet_vision_service.py
├── signature.json
├── squeezenet.onnx
└── synset.txt

1 directory, 6 files
$ model-archiver --model-name model --model-path . --handler mxnet_vision_service:handle -f
[1]    926 illegal hardware instruction (core dumped)  model-archiver --model-name model --model-path . --handler  -f
```
 
The `pip show model-archiver` output: 
```
Name: model-archiver
Version: 1.0.2
Summary: Model Archiver is used for creating archives of trained neural net models that can be consumed by MXNet-Model-Server inference
Home-page: https://github.com/awslabs/mxnet-model-server/model-archiver/
Author: MXNet SDK team
Author-email: noreply@amazon.com
License: Apache License Version 2.0
Location: /home/amsha/virtualenv/maxnetmodelserver/lib/python3.7/site-packages
Requires: future, enum-compat
Required-by: mxnet-model-server
```

**Comment by vdantu** [comment]
@ahmed-shariff : I downloaded the artifacts you had uploaded to google drive. I don't see core dump, but I do see these errors:

```
ERROR - Failed to import model.onnx file to onnx. Verify if the model file is valid
Traceback (most recent call last):
  File "/py3env/bin/model-archiver", line 11, in <module>
    load_entry_point('model-archiver', 'console_scripts', 'model-archiver')()
  File "/Users/dummy/model-archiver/model_archiver/model_packaging.py", line 63, in generate_model_archive
    package_model(args, manifest=manifest)
  File "/Users/dummy/model-archiver/model_archiver/model_packaging.py", line 40, in package_model
    t, files_to_exclude = ModelExportUtils.check_custom_model_types(model_path, model_name)
  File "/Users/dummy/model-archiver/model_archiver/model_packaging_utils.py", line 93, in check_custom_model_types
    symbol_file, params_file = ModelExportUtils.convert_onnx_model(model_path, onnx_file, model_name)
  File "/Users/dummy/model-archiver/model_archiver/model_packaging_utils.py", line 165, in convert_onnx_model
    sym, arg_params, aux_params = onnx_mxnet.import_model(os.path.join(model_path, onnx_file))
  File "/py3env/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/import_model.py", line 59, in import_model
    sym, arg_params, aux_params = graph.from_onnx(model_proto.graph)
  File "/py3env/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 115, in from_onnx
    mxnet_sym = self._convert_operator(node_name, op_name, onnx_attr, inputs)
  File "/py3env/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 61, in _convert_operator
    op_name, new_attrs, inputs = convert_map[op_name](attrs, inputs, self)
  File "/py3env/lib/python3.6/site-packages/mxnet/contrib/onnx/onnx2mx/_op_translations.py", line 434, in reshape
    reshape_shape = list(proto_obj._params[inputs[1].name].asnumpy())
```
So, the ONNX model in that package is incorrect. You might want to verify if this model is proper.
--model-name shouldn't matter. You should be able to give any model name and it should technically work.


What is your host configuration? Are you running on ec2 instances or on your local host? Also, what are the CPU and memory available in the host. I am not able to recreate this error and would like to recreate it.

**Comment by ahmed-shariff** [comment]
I was able to run the same model on onnxruntime and the onnx caffe backend.
I am running this on a local host for now. It only havs 4GB memory with an i5 (A rusty old thinkpad). I'll try it on another pc as soon as possible and let you know what comes of it.

**Comment by ahmed-shariff** [comment]
I executed the scripts in a different pc, and the same error you got. Will investigate further and update.

The error output:
```
Traceback (most recent call last):
  File "/home/user/.conda/envs/torch/bin/model-archiver", line 10, in <module>
    sys.exit(generate_model_archive())
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/model_archiver/model_packaging.py", line 61, in generate_model_archive
    package_model(args, manifest=manifest)
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/model_archiver/model_packaging.py", line 38, in package_model
    t, files_to_exclude = ModelExportUtils.check_custom_model_types(model_path, model_name)
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/model_archiver/model_packaging_utils.py", line 91, in check_custom_model_types
    symbol_file, params_file = ModelExportUtils.convert_onnx_model(model_path, onnx_file, model_name)
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/model_archiver/model_packaging_utils.py", line 163, in convert_onnx_model
    sym, arg_params, aux_params = onnx_mxnet.import_model(os.path.join(model_path, onnx_file))
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/mxnet/contrib/onnx/onnx2mx/import_model.py", line 59, in import_model
    sym, arg_params, aux_params = graph.from_onnx(model_proto.graph)
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 115, in from_onnx
    mxnet_sym = self._convert_operator(node_name, op_name, onnx_attr, inputs)
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/mxnet/contrib/onnx/onnx2mx/import_onnx.py", line 61, in _convert_operator
    op_name, new_attrs, inputs = convert_map[op_name](attrs, inputs, self)
  File "/home/user/.conda/envs/torch/lib/python3.7/site-packages/mxnet/contrib/onnx/onnx2mx/_op_translations.py", line 434, in reshape
    reshape_shape = list(proto_obj._params[inputs[1].name].asnumpy())
KeyError: 'concat0'
```

**Comment by vdantu** [comment]
@ahmed-shariff : Awesome. Do keep us posted about your findings. This might be helpful for the general community :)

**Comment by vdantu** [comment]
@ahmed-shariff : How are the experimentations coming along? Do you need any help?

**Comment by ahmed-shariff** [comment]
Seems it's a problem with the op translation in mxnet with onnx, and it has been reported in mxnet: https://github.com/apache/incubator-mxnet/issues/14916

**Comment by vdantu** [comment]
@ahmed-shariff : Oh. Interesting find. We can track this issue with MXNet then right? Should we close this issue in MMS repo?

**Comment by ahmed-shariff** [comment]
Yes, it is a mxnet issue it seems. Closing issue. Thank you for the assist :D
